version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: cluster2-01
    environment:
      - node.name=cluster2-01
      - cluster.name=es-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9300:9200
    networks:
      - es-cluster1
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: cluster2-02
    environment:
      - node.name=cluster2-02
      - cluster.name=es-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - es-cluster1
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: cluster2-03
    environment:
      - node.name=cluster1-03
      - cluster.name=es-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - es-cluster1

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  es-cluster1:
    driver: bridge
